//
// Created by Jason Torrence on 10/24/2019.
//

#ifndef REAL_ESTATE_TYCOON_APARTMENTCOMPLEX_H
#define REAL_ESTATE_TYCOON_APARTMENTCOMPLEX_H


class ApartmentComplex {

};


#endif //REAL_ESTATE_TYCOON_APARTMENTCOMPLEX_H
